[tool.ruff]
line-length = 100
target-version = "py311"
src = ["dags", "services", "tests"]

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
ignore = ["E203", "E266", "E501"]
